from colorPrint import cprint
print()
cprint("§_SUCCESS_SUCCESS")
cprint("§_INFO_INFO")
cprint("§_WARNING_WARNING")
cprint("§_DANGER_DANGER")
cprint("§_ERROR_ERROR")
cprint("§-SUCCESS-SUCCESS")
cprint("§-INFO-INFO")
cprint("§-WARNING-WARNING")
cprint("§-DANGER-DANGER")
cprint("§-ERROR-ERROR")
print()